[doc] Update Contributing section
TRIQS/triqs pull request #736
Opened 2019-08-15 19:42 UTC by amoutenet

Write "How to make a pull request section" + minor updates in "How to contribute to the documentation"

2019-08-16 18:24 UTC, Wentzell requested changes
Thank you Alice! This looks great!
I just had a few minor remarks.

2019-08-16 18:24 UTC, Wentzell commented on doc/contributing/documentation.rst
> +As for code contribution, you are going to submit your changes as a pull request from the unstable branch
```suggestion
As for code contribution, you are going to submit your changes as a pull request to the unstable branch 
```

2019-08-16 18:24 UTC, Wentzell commented on doc/contributing/pull_request.rst
> +and this page is here to guide you through this process
```suggestion
and this page is here to guide you through this process.
```

2019-08-16 18:24 UTC, Wentzell commented on doc/contributing/pull_request.rst
> +go to `Pull requests`, and `New pull request`. Be sure to select unstable as the base branch.
```suggestion
and click `New pull request`. Be sure to select unstable as the target branch and my_first_PR as the source branch.
```

2019-08-16 18:24 UTC, Wentzell commented on doc/contributing/pull_request.rst
> +When you consider your pull request ready to be reviewed by TRIQS developers, go to the `triqs github <https://github.com/TRIQS/triqs>`_ and
```suggestion
When you consider your pull request ready to be reviewed by TRIQS developers, go to the github page of your fork
```

2019-08-19 20:51 UTC, amoutenet commented
@Wentzell thank you for the review, I applied the changes!

2019-08-20 15:23 UTC, merged