[doc] Tutorials > User guide, design section [WIP]
TRIQS/triqs pull request #737
Opened 2019-08-15 22:09 UTC by amoutenet

We change the Tutorials section in a "User guide" section that aims at giving a broad overview of the main classes and applications of TRIQS through code snippets ready-to-use.

The spirit of this section is explained in the additional paragraph of index.rst, where we tell new users to: 
- First install triqs
- Then do the Python tutorials available on the GitHub
- Browse through the User guide codes to get a sense of what is in the library

Of course the User guide section contains a warning saying that this is not meant to replace the full reference.

2019-08-16 18:31 UTC, Wentzell requested changes
Thank you Alice! I like the changes!
I think its great to have the getting started section already on the main-page.
I just had a few minor corrections to your commit.

2019-08-16 18:31 UTC, Wentzell commented on doc/index.rst
> +or run them locally after setting up triqs on your computer.
```suggestion
or run them locally after setting up TRIQS on your computer.
```

2019-08-16 18:31 UTC, Wentzell commented on doc/userguide.rst
> +     or run them locally after setting up triqs on your computer.
```suggestion
     or run them locally after setting up TRIQS on your computer.
```

2019-08-19 20:53 UTC, amoutenet commented
@Wentzell thank you very much, here is the updated PR!

2019-08-20 15:21 UTC, merged