Test for issue when multiplying Gfs with different dimensions
TRIQS/triqs pull request #794
Opened 2020-10-08 16:43 UTC by the-hampel

When multiplying two Green functions with different shape, for example for downfolding / upfolding purposes, triqs gives an error, that the dimensions do not match. A simple example would be: 
```
from triqs.gf import *

iw_mesh = MeshImFreq(beta=40, S='Fermion', n_max=1025)
# create upfolded Gf with 5x5 dim
G_upf = Gf(mesh=iw_mesh, target_shape=[5, 5])
# create downfolded target Gf with 3x3 dim
G_dnf = Gf(mesh=iw_mesh, target_shape=[3, 3])

# downfolding projector from the 5 to 3 orb
downfolding = Gf(mesh=iw_mesh, target_shape=[3,5])

# the downfolding / projection from 5 to 3 orbitals fails
# this should work since we are doing [3,5]x[5,5]x[5,3]
G_dnf  << downfolding*(G_upf*downfolding.transpose().conjugate())
```
This should work as the multiplication of matrices of these dimensions makes sense and is often used for downfolding. The code gives the error:
```
Traceback (most recent call last):
File "/mnt/home/ahampel/Dropbox/git/triqs3/triqs.src/test/python/base/issue_gf_mult_dim.py", line 36, in <module>
G_dnf  << downfolding*(G_upf*downfolding.transpose().conjugate())
File "/mnt/home/ahampel/git/triqs-3.x_unstable/triqs_fix_gf_mult.build/python/triqs/gf/gf.py", line 537, in __mul__
     c.__imul__impl(y)
File "/mnt/home/ahampel/git/triqs-3.x_unstable/triqs_fix_gf_mult.build/python/triqs/gf/gf.py", line 494, in __imul__impl
     d_self[n] = np.dot(d_self[n], d_args[n]) # put to C if too slow.
ValueError: could not broadcast input array from shape (5,3) into shape (5,5)
```
Triqs expect the outcoming Gf to have the same shape as the first input Gf.

This PR adds a simple test that fails at the moment and should be fixed.

Thanks.

2021-10-08 19:46 UTC, Wentzell requested changes

2021-10-08 19:46 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                    d_c[n] = np.dot(d_self[n], d_y[n])
Why all the reshapes? Shouldn't this just be
```suggestion
                np.dot(self.data, y.data, out=c.data)
```
c.f. https://numpy.org/doc/stable/reference/generated/numpy.dot.html
Quote:

> `numpy.dot(a, b, out=None)`
> If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:
> `dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])`

2021-10-12 14:23 UTC, jkarp314 commented
@Wentzell I think the PR should be ready now

2021-10-25 16:27 UTC, Wentzell requested changes

2021-10-25 16:27 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                    name = self.name)
```suggestion
            c = Gf(mesh=Gf._combine_mesh_mul(self._mesh, y.mesh),
                   target_shape=[self.target_shape[0], y.target_shape[1]])
```
I don't think we should make a distinction here. Note that we have deprecated the use of `self._indices` and the name of the Gf should not propagate through multiplication.

2021-10-25 16:27 UTC, Wentzell commented on python/triqs/gf/gf.py
> +            np.matmul(self.data, y.data, out=c.data)
This actually requires `self.target_rank == 2` to make any sense. We should check this both here and in the `imul`.
Also, the `self.target_rank == 0` case (i.e. scalar product) should be properly handled and tested for both cases `mul` and `imul`.

2021-10-28 18:33 UTC, Wentzell requested changes

2021-10-28 18:33 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                    "the argument is a nonsaure matrix. Use regular multiplication instead."
```suggestion
                    "the argument is a non-square matrix. Use regular multiplication instead."
```

2021-10-28 18:33 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                    self.data[:] = self.data*(np.broadcast_to(arg.data, self.data.T.shape).T)
Why not just:
```suggestion
                    self.data *= arg.data[..., None, None]
```

2021-10-28 18:33 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                c = Gf(mesh=Gf._combine_mesh_mul(self._mesh, y.mesh),
Define `result_mesh` using `_combine_mesh_mul` before going into the various cases?

2021-10-28 18:33 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                c.data[:] = self.data*(np.broadcast_to(y.data, self.data.T.shape).T)
```suggestion
                c.data[:] = self.data * y.data[..., None, None]
```

2021-10-28 18:33 UTC, Wentzell commented on python/triqs/gf/gf.py
> +                c.data[:] = y.data*(np.broadcast_to(self.data, y.data.T.shape).T)
```suggestion
                c.data[:] = self.data[..., None, None] * y.data
```

2021-10-28 18:33 UTC, Wentzell commented on test/python/base/gf_block.py
> +        B4 = BlockGf(name_list=['0', '1'], block_list=[G1*G3, G2*G4])
```suggestion
        B4 = BlockGf(name_list=['0', '1'], block_list=[G1*G3, G2*G4])
        
        assert_block2_gfs_are_close(B3, B4)
```

2021-10-28 18:33 UTC, Wentzell commented on test/python/base/gf_base_op.py
> +        assert_gfs_are_close(G_mult, G_loop)
Maybe add comparison also with exact result, i.e. `G3 << inverse(iOmega_n + 2) * inverse(iOmega_n - 2)`

2021-11-01 18:03 UTC, merged

2021-11-01 18:03 UTC, Wentzell commented
Thank you @jkarp314