U_matrix supports wannier90 basis
TRIQS/triqs pull request #860
Opened 2022-10-10 20:33 UTC by harrisonlabollita

The functions that transform the Umatrix: ``spherical_to_cubic``, ``t2g_submatrix``, and ``eg_submatrix`` now support ``convention = "wannier90"``, where the d-shell is ordered as ("z^2", "xz", "yz", "x^2-y^2", "xy").

2022-10-25 12:09 UTC, harrisonlabollita commented
Conventions have been explicitly named for the construction of the ``U_matrix`` that correspond to popular DFT codes. The previous default convention `` '' `` (an empty string) has been renamed to ``triqs`` to avoid any ambiguity.

2022-10-25 13:23 UTC, the-hampel approved these changes

2022-10-25 13:26 UTC, the-hampel requested changes
There is a problem with an indented block: 
```
Traceback (most recent call last):

  File "/src/triqs/test/python/operators.py", line 22, in <module>

    from triqs.operators.util import *

  File "/home/build/triqs/python/triqs/operators/util/__init__.py", line 23, in <module>

    from .observables import *

  File "/home/build/triqs/python/triqs/operators/util/observables.py", line 24, in <module>

    from triqs.operators.util.U_matrix import spherical_to_cubic

  File "/home/build/triqs/python/triqs/operators/util/U_matrix.py", line 235

    else:

    ^

IndentationError: expected an indented block
```
Can you please fix that and recheck. The rest looks very good! Thanks!

2022-10-26 16:17 UTC, the-hampel commented
Okay now everything looks good. Maybe @Wentzell can have a quick look, thank you.

2022-10-27 16:44 UTC, the-hampel approved these changes

2022-11-02 19:07 UTC, Wentzell commented
Thank you @harrisonlabollita for these improvements!

2022-11-02 19:07 UTC, Wentzell approved these changes

2022-11-02 19:22 UTC, merged